### ISSUE TITLE
A provider named "vbox" could not be found in the official repository.

### ISSUE THREAD

**Issue by kamal2222ahmed** [mfcastellani/terraform-provider-vbox#1]
trying to run the example in this repo.
```
main.tf
provider "vbox" {
  user = "Nome do usuário"
  token = "Token do usuário"
}

resource "vbox_disk" "meu_disco" {
  size = 1024
  name = "awesome_disk"
}

resource "vbox_instance" "minha_imagem" {
  name = "awesome_image"
  osname = "Ubuntu"
  diskname = "${vbox_disk.meu_disco.name}"
}
```
$ terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Provider "vbox" not available for installation.

A provider named "vbox" could not be found in the official repository.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

**Comment by mfcastellani** [comment]
Hi @kamal2222ahmed 

You need to manually copy the generated binary to the providers folder, as explained at the README for the project.

Thanks!
